#ifndef _HUD_CONFIG_H_
#define _HUD_CONFIG_H_

#include <stdint.h>
#include <stdbool.h>

#define HUD_PIN_CANBUS_RX  GPIO_NUM_25
#define HUD_PIN_CANBUS_TX  GPIO_NUM_26

#define HUD_PIN_AMBLIGHT   GPIO_NUM_33

#define HUD_PIN_SD_CS      GPIO_NUM_5

#define HUD_PIN_STRIP_DATA GPIO_NUM_15
#define HUD_PIN_STRIP_CLK  GPIO_NUM_27

#define HUD_PIN_HEART_DATA GPIO_NUM_2
#define HUD_PIN_HEART_CLK  GPIO_NUM_12
#define HUD_PIN_HEART_PWR  GPIO_NUM_13

#define SPEED_TICK_SPACING   6

#define LED_STRIP_SIZE       ((8 * SPEED_TICK_SPACING) + 1)
#define LED_STRIP_OFFSET     1
#define LED_STRIP_TAIL       1
#define LED_STRIP_SIZE_VIRTUAL (LED_STRIP_OFFSET + LED_STRIP_SIZE + LED_STRIP_TAIL)

#define VOLT_TICK_SPACING    9
#define SPEED_NEEDLE_SIZE    2
#define SPEED_MAX            120
#define FADING_HEAD

#define HEARTBEAT_BRIGHTNESS 64

#define BATTLOG_WRITE_TIMEOUT 300
#define BATTLOG_WRITE_ERR_MAX 3
#define BATTLOG_SYNC_INTERVAL 5000

// below config options should all be disabled when the project is finished
//#define ENABLE_BRINGUP_TESTS
//#define DEBUG_STRIP
//#define ENABLE_TEST_PRINT_DB
//#define ENABLE_TEST_PRINT_SPEED_FAST
//#define ENABLE_SPEED_CALIBRATION
//#define DISABLE_SPEED_PREDICTION
//#define ENABLE_SPEED_PREDICTION_JERK_FILTER
//#define DISABLE_WIFI_SLEEP
//#define DISABLE_DEEP_SLEEP
//#define FORCE_CARD_GOOD
//#define FORCE_SETTINGS_DEFAULT

#endif
